version: '3.4'

services:
  orderssqlite:
    image: ${DOCKER_REGISTRY-}orderssqlite
    build:
      context: .
      dockerfile: OrdersSQLite/Dockerfile

  bkprojsqlserver:
    links:  
      - DockerMSSQL
    image: ${DOCKER_REGISTRY-}bkprojsqlserver
    build:
      context: .
      dockerfile: BKProjSqlServer/Dockerfile

  DockerMSSQL:
    image: microsoft/mssql-server-linux:2017-latest
    hostname: 'DockerMSSQL'
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: "Borazjan11"
    volumes:
      - ./data/mssql:/var/opt/mssql3
    ports:
      - '1433:1433'
    expose:
      - 1433


